### ISSUE TITLE
How to handle 422 errors (fork PRs coverage?)

### ISSUE THREAD

**Issue by skrdgraph** [coverallsapp/github-action#150]
Referencing -> https://github.com/lemurheavy/coveralls-public/issues/1695

Hey Coveralls team, 

We are having an issue on our OSS projects [Badger](https://github.com/dgraph-io/badger) & [Dgraph](https://github.com/dgraph-io/dgraph) with coveralls. The error message is as follows:
```
Run goveralls -coverprofile=cover.out
bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
Error: Process completed with exit code 1.
```

We have noticed that this happens at random. We have mostly seen this happening on contributions from outside authors from their `forks`. Internal author contributions via branch/PR seems to work fine. Would it be possible to get a little help here?

Our workflows use GitHub Actions, and are available [here](https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-dgraph-code-coverage.yml#L71-L74) & [here](https://github.com/dgraph-io/badger/blob/main/.github/workflows/ci-badger-tests.yml#L34-L39)

Some sample errors include (mostly from outside authors' PRs):
- https://github.com/dgraph-io/badger/pull/1875
- https://github.com/dgraph-io/badger/pull/1850
- https://github.com/dgraph-io/dgraph/pull/8650
- https://github.com/dgraph-io/dgraph/pull/8613

The failed jobs in those links all have the same error message as above. Looking forward to your help & guidance here. 

What we have tried: 
- resetting the token https://github.com/dgraph-io/badger/pull/1849#issuecomment-1402455920
- read up other similar issues https://github.com/dgraph-io/badger/pull/1849#issuecomment-1402475775
- force the service flag to GitHub https://github.com/dgraph-io/badger/pull/1849/files#diff-979eaac98bd181c1c298401668d7a399a75c136b92aa922b4a124d81b41ed534R39

cc: @joshua-goldstein

**Comment by mrexox** [comment]
Hey! Thank you for the issue. This is very weird that the behavior is random. I guess that it happens [here](https://github.com/dgraph-io/badger/actions/runs/4127466005/jobs/7130710821) because there is a `-service=github`. And coveralls has an awkward bug which required repo token to be `${{ secrets.GITHUB_TOKEN }}` in that case (only when explicitly specified `service_name: 'github'`.

We are going to fix this behavior, but as a workaround I'd recommend either not to use explicit `-service` parameter, or use it with `-repotoken=${{ secrets.GITHUB_TOKEN }}`. Please, write if it helps, if not - I will escalate the bug fix.

**Comment by skrdgraph** [comment]
Hey @mrexox thanks for the help. The real issue has been described here: https://github.com/dgraph-io/badger/pull/1894

It's documented here https://github.com/dgraph-io/badger/pull/1894#issue-1605540554

We are going to close this issue, as we are unblocked.
