### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by JoeCohen** [coverallsapp/github-action#201]
The GitHub action causes this deprecation warning in Github Actions:
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: coverallsapp/github-action@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by dakujem** [comment]
I accidentally found out the issue may be patched by using a fixed version, like `coverallsapp/github-action@v2.3.0`.

There should be a better way though.  
It may be a simple matter of updating the `latest` or `master` tags, if provided.

**Comment by Minoru** [comment]
@dakujem is spot-on: years ago, Coveralls' README suggested to use `coverallsapp/github-action@master`, so I did. Then Coveralls switched the default branch to "main", and stopped updating "master". (This hasn't been communicated anywhere I could find: there's no changelog; the commit log and README don't mention it either.) Now "master" finally got old enough to trigger warnings from GitHub Actions.

**Comment by afinetooth** [comment]
Apologies for the confusion and inconvenience here.

In order to replicate the "latest version" feature of `@master` for `v1.x` of our Action, we created a new `main` branch for `v2.x`. So `@main` should keep you up-to-date with the latest `2.x` release.

We still have many users on `v1.x`, so we leveraged the migration from `master` to `main` for this opportunity.

**Comment by dakujem** [comment]
It really did not occur to me to use `main` instead of `master`... But thanks, now i can at least get rid of the `@2.3.0` fixed version.

**Comment by afinetooth** [comment]
Totally understand. I believe it's in the release notes, but we should have broadcast the change more widely.

We don't require email addresses to register, since we're all OAuth via your SCM (GitHub, Gitlab or Bitbucket), so we don't have a way to send product updates, besides to subscribers:
https://coveralls.io/announcements.
