### ISSUE TITLE
Not working on Mac OS

### ISSUE THREAD

**Issue by aburrell** [coverallsapp/github-action#202]
I tried to use this with my project ([ocbpy](https://github.com/aburrell/ocbpy/)) and it failed for mac OS with the following error:

```
Run coverallsapp/github-action@v2
Run brew tap coverallsapp/coveralls --quiet
==> Fetching dependencies for coverallsapp/coveralls/coveralls: bdw-gc
==> Fetching bdw-gc
==> Fetching coverallsapp/coveralls/coveralls
==> Installing coveralls from coverallsapp/coveralls
==> Installing dependencies for coverallsapp/coveralls/coveralls: bdw-gc
==> Installing coverallsapp/coveralls/coveralls dependency: bdw-gc
🍺  /usr/local/Cellar/bdw-gc/8.2.6: 73 files, 1.6MB
==> Installing coverallsapp/coveralls/coveralls
🍺  /usr/local/Cellar/coveralls/0.6.6: 5 files, 1.2MB
Run coveralls report        
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/bin/coveralls", line 5, in <module>
    from coveralls.cli import main
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/__init__.py", line 2, in <module>
    from .api import Coveralls
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/api.py", line 13, in <module>
    from .reporter import CoverallReporter
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/reporter.py", line 10, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter' from 'coverage.report' (/Users/runner/hostedtoolcache/Python/3.8.18/x[64](https://github.com/aburrell/ocbpy/actions/runs/8482430217/job/23242927874#step:10:67)/lib/python3.8/site-packages/coverage/report.py)
Error: Process completed with exit code 1.
```

When I use `coveralls-reporter`, I do not encounter any problems.

**Comment by sneakers-the-rat** [comment]
Still the case with `2.3.0`, although getting a slightly different error: https://github.com/p2p-ld/numpydantic/actions/runs/10188917927/job/28186002838

```
Run coverallsapp/github-action@v2.3.0
Run brew tap coverallsapp/coveralls --quiet
==> Fetching dependencies for coverallsapp/coveralls/coveralls: bdw-gc, z3, llvm and crystal
==> Fetching bdw-gc
==> Fetching z3
==> Fetching llvm
==> Fetching crystal
==> Fetching coverallsapp/coveralls/coveralls
==> Installing coveralls from coverallsapp/coveralls
==> Installing dependencies for coverallsapp/coveralls/coveralls: bdw-gc, z3, llvm and crystal
==> Installing coverallsapp/coveralls/coveralls dependency: bdw-gc
🍺  /opt/homebrew/Cellar/bdw-gc/8.2.6: 74 files, 1.8MB
==> Installing coverallsapp/coveralls/coveralls dependency: z3
🍺  /opt/homebrew/Cellar/z3/4.13.0: 120 files, 31.1MB
==> Installing coverallsapp/coveralls/coveralls dependency: llvm
🍺  /opt/homebrew/Cellar/llvm/18.1.8: 7,722 files, 1.8GB
==> Installing coverallsapp/coveralls/coveralls dependency: crystal
🍺  /opt/homebrew/Cellar/crystal/1.13.1: 1,473 files, 22.4MB
==> Installing coverallsapp/coveralls/coveralls
==> shards build coveralls --production --release --no-debug
==> strip ./bin/coveralls
🍺  /opt/homebrew/Cellar/coveralls/0.6.12: 6 files, 1.1MB, built in 20 seconds
Run coveralls report        
  coveralls report        
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.9.13/arm64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    COVERALLS_DEBUG: false
    COVERALLS_CARRYFORWARD_FLAGS: 
    COVERALLS_FLAG_NAME: run-macos-latest->=2.0.0-3.9
    COVERALLS_PARALLEL: true
    COVERALLS_ENDPOINT: https://coveralls.io/
    COVERALLS_GIT_BRANCH: 
    COVERALLS_GIT_COMMIT: 
    COVERALLS_REPO_TOKEN: ***
    COVERALLS_COMPARE_REF: 
    COVERALLS_COMPARE_SHA: 
    COVERALLS_SOURCE_HEADER: github-action
Usage:
    coveralls [options]
    coveralls debug [options]
Error: Process completed with exit code 1.
```

running coveralls locally from the homebrew tap install i'm getting the same thing. the mac version wants me to just run `coveralls` and doesn't have a `coveralls report`

**Comment by afinetooth** [comment]
Hi @sneakers-the-rat (Cc: @aburrell). Is an earlier version of the [GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) working for you.

**Comment by sneakers-the-rat** [comment]
idk i just did this https://github.com/p2p-ld/numpydantic/blob/880dafb151e793ce2211d708f0f762188948caa2/.github/workflows/tests.yml#L54

**Comment by aburrell** [comment]
@afinetooth No previous versions of the GH Action worked for me.

**Comment by afinetooth** [comment]
Thanks @aburrell @sneakers-the-rat.

I think these issues may be due to a namespace conflict on your runners---ie, two executables with the name `coveralls` in different locations, leading to ambiguity in which one is used.

I was able to reproduce this situation on my Mac between the `coveralls` binary and the `coveralls` rubygem. 

After a fresh install of the `coveralls` binary (Coverage Reporter) via homebrew:

```
brew tap coverallsapp/coveralls
brew install coveralls
```

When I try to run `coveralls report` I get this error:

```
coveralls report
Could not locate Gemfile or .bundle/ directory
```

Which indicates my Terminal thinks I'm looking for the gem.

Furthermore, `which coveralls` reveals the gem installation:

```
which coveralls
/Users/jameskessler/.gem/ruby/3.1.3/bin/coveralls
```

While `brew info coveralls` reveals the binary's location:

```
brew info coveralls
brew info coveralls
==> coverallsapp/coveralls/coveralls: stable 0.6.12
Self-contained, universal coverage uploader for Coveralls
https://github.com/coverallsapp/coverage-reporter
Installed
/opt/homebrew/Cellar/coveralls/0.6.12 (6 files, 1.1MB) [...]
```

My guess is you both have a `coveralls` python package installed. Could that be the case?

For my case there are two solutions:

1) Run the binary with its full path:

```
/opt/homebrew/bin/coveralls report                                                   
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.12
[...]
```

Not very helpful in a CI situation though, where the coverage reporter is being installed under-the-hood by the github-action.

2) Make sure homebrew is first in my path before I call the binary executable:

```
export PATH="/opt/homebrew/bin:$PATH"
jameskessler@Jamess-Mac-Studio ~ % coveralls report
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.12
[...]
```

Which is more doable in the CI context.

In your cases, presuming the other `coveralls` is the python package, which is the [Coveralls Language Integration](https://docs.coveralls.io/integrations#language-integrations) known as [coveralls-python](https://github.com/TheKevJames/coveralls-python).

Technically, if you are using an [Official Integration](https://docs.coveralls.io/integrations#official-integrations)---either our [GitHub Action](https://github.com/coverallsapp/github-action) or the [Coverage Reporter](https://github.com/coverallsapp/coverage-reporter) directly---you don't need the [coveralls-python](https://github.com/TheKevJames/coveralls-python) [Language Integration](https://docs.coveralls.io/integrations#language-integrations) because the official integration will find and parse and upload your original python coverage report.

That said, this is the recommended procedure and configuration for python projects with the [Action](https://github.com/coverallsapp/github-action or the [Reporter](https://github.com/coverallsapp/coverage-reporter):

### GitHub Action

1. Convert your original python coverage report (`.coverage` file) into Cobertura XML format using `coverage xml`.
2. Specify `cobertura` format in your upload step(s):

```
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2.3.0
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
          format: cobertura
          debug: true
```

That will make the action ignore your `.coverage` file and only process your `coverage.xml` file. That format is consistently our best result for python coverage reports. In fact, if you upload a `.coverage` file only, we look for `coverage.py` in your immediate environment and try to perform that conversion.

**Comment by aburrell** [comment]
This resolved things for me.
