### ISSUE TITLE
Coveralls keeps posting PR coverage reports instead of editing the current one

### ISSUE THREAD

**Issue by ITaluone** [coverallsapp/github-action#215]
See e.g. here: https://github.com/fluentassertions/fluentassertions/pull/2676

See how many _new_ coveralls coverage report comments has been posted. I also noticed that apparently after the second edit (meaning three comment versions) a new one is posted.

Is this a miss configuration?

**Comment by afinetooth** [comment]
Hi @ITaluone. Thanks for reporting this. 

It is a known issue that's in the backlog for our current sprint. We hope to resolve it this week.

In the meantime, apologies for the inconvenience. I'll update this issue when it's fixed.

**Comment by ITaluone** [comment]
Thank you for your quick response.

Yeah, thanks

**Comment by afinetooth** [comment]
@ITaluone and anyone else affected by this issue, I wanted to provide an update and ETA:
 
**Update**:
The new ETA for resolution of this issue is this coming **Mon, Jul 8**. We expect that to be the latest date when this issue will be resolved. We are working to resolve it sooner.

An explanation is included below if you're interested.

We apologize for the continued inconvenience and want to assure you we're doing what we can to resolve this issue as quickly as possible.

**Details**:
To resolve this issue, we need to change column types in several database tables to increase their storage capacity. This is in response to new pull request comment IDs coming to us from GitHub that exceed our previous storage capacity.

With a codebase that's been in production for over 13 years, many of our challenges are ones of scale. In this case, we attempted to make the column changes in several tables during a scheduled maintenance window this past weekend. However, with tens of millions of rows in each affected table, we were unable to execute the changes safely and completely in our planned 4-hr. window.

As a result, we've switched to a zero-downtime approach that we'll execute this week, but the approach still needs to be performed in several stages that we prefer to schedule during off-peak hours, each of which we expect to take 0.5-1 day.

Should we encounter any unexpected issues and foresee the need for it, we'll schedule another maintenance window for Sat night, this coming weekend; but for now, the effort has begun and all is well. Should that occur, you can follow the status here: https://status.coveralls.io/

**Comment by afinetooth** [comment]
@ITaluone @Kixunil 

This issue of receiving MULTIPLE PR COMMENTS from Coveralls should now be resolved. 

Going forward, Coveralls should always update the last comment with its latest comment.

Please let me know if you experience multiple PR comments on any PRs that were **created after Sun Jul 7 at ~7p PDT**. PRs created before that time may have received more than one comment.

**Comment by tomasMizera** [comment]
Thanks guys!
