### ISSUE TITLE
how to get coverage rate directly in github action

### ISSUE THREAD

**Issue by Young-Flash** [coverallsapp/github-action#223]
Is there a way to get coverage rate in github action, or with coveralls cli tool?(instead of open the link in response ✅ API Response: {"message":"Job #10957286536.1","url":"https://coveralls.io/jobs/xxxxx"}) then we can failed the ci when coverage rate low than given value. Thanks
<img width="362" alt="image" src="https://github.com/user-attachments/assets/96bc7dae-4464-438f-8f8e-bcd7b6b2c0e1">

**Comment by afinetooth** [comment]
Hi @Young-Flash.

Yes, and I'll explain how below, but first, there's an easier way. Coveralls has built-in Notification features for that use case, including a way to set thresholds for GitHub Status Updates that will turn them into Status Checks, which can block PR merging if your PRs don't meet coverage requirements.

You can read about Status Update Notifications here:
https://docs.coveralls.io/app-notifications#status-updates

Where you'll see how to set the two basic coverage thresholds:

- **Fail threshold** (**aka**. **Covealls threshold**): Coverage must reach this level or status check will fail.
- **Change threshold** (**aka**. **Drop threshold**): If coverage changes/drops more than this amount, status check will fail.

FYI, since [that doc](https://docs.coveralls.io/app-notifications#status-updates) was written, we've added other thresholds for additional types of status checks, like "patch" status updates that can set a threshold for coverage % for just the _patch_ (new code in your PR), etc.

You'll find all those settings, which can be set in a general way, on any of your [Repo Settings](https://docs.coveralls.io/app-ui#repo-settings) pages in Coveralls.io.

But you can also set those at a higher level of granularity by using a `.coveralls.yml` file at the root of your project. (Let me know if you have questions about that.)

Finally, if for some reason you don't want to use Coveralls Notifications features, you can request information from the [Coveralls API](https://docs.coveralls.io/api-introduction) from your workflows (or wherever). You'll want to check out [JSON-Format Web Data](https://docs.coveralls.io/api-introduction#json-format-web-data), which you can preview from the web app by adding a `.json` extension to any Coveralls.io web page, then request the same data via the API, by making a request like this:

```

```
