### ISSUE TITLE
Coveralls Github Action executed from a workflow_run event

### ISSUE THREAD

**Issue by elchininet** [coverallsapp/github-action#236]
In one of my repos I have the next set-up in one of my workflows:

1. A pull request is open
2. A job is triggered using the `pull_request` event and using a secret it runs some integration tests in a docker container and creates a coverage
3. The coverage is submitted to Coveralls

This works great when the pull request is open from the same repository. If the pull request is open from a fork, `pull_request` runs in a secure context in which there is no access to the secrets so it fails. [The Github recommendation](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/) to avoid using `pull_request_target` from an external fork is to trigger another workflow using `workflow_run`, so I did the next:

1. A pull request is open (in this case from a fork)
5. A job is triggered using the `pull_request` event and it builds the JavaScript bundle needed for the integration tests and uploads it as an artifact.
6. A second job is executed with `workflow_run` when the previous job finishes, it downloads the artifact bundle, run the integration tests and creates a coverage (this runs in the context of the master branch)

Now, the issue comes when I want to upload the coverage result to Coveralls because Coveralls thinks that I want to upload the coverage from master (because it is the context in which it is running). So this provokes that the comment never reaches the merge request. I tried to make use of the `git-branch` and `git-commit` options but it returns an error:

```bash
Error:  "2024-11-26T00:11:15.550Z"  'error from getOptions'
Error: Error: Command failed: git cat-file -p 1f775226a40a72c11cb92da616120f80d9fde9cb
fatal: Not a valid object name 1f775226a40a72c11cb92da616120f80d9fde9cb
```

From the `workflow_run` job, I am able to update the MR checks using the [LouisBrunner/checks-action](https://github.com/LouisBrunner/checks-action) and the `sha` option (providing the `sha` of the MR head), but this doesn't work with Coveralls. Do you have a way to solve this? Or do you have another approach that would make my use case work keeping the security.

Regards and thanks in advance

**Comment by afinetooth** [comment]
Hi @elchininet.

Yes, those options should work, but only with newer versions of our [official integrations](https://docs.coveralls.io/integrations#official-integrations). (It looks like you may be using a [language integration](https://docs.coveralls.io/integrations#language-integrations) for [JavaScript/Node](https://docs.coveralls.io/javascript) that may or may not support newer features of the Coveralls API.)

So, since you're on **GitHub Actions**, I'd recommend using `v2` of our [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action), which uses our [Universal Coverage Reporter](https://github.com/coverallsapp/coverage-reporter) under-the-hood, which supports all Coveralls API features.

The [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) will let you override the default **branch** and **commit SHA** with the [`git-branch`](https://github.com/marketplace/actions/coveralls-github-action#:~:text=git%2Dbranch,the%20branch%20name.) and [`git-commit`](https://github.com/marketplace/actions/coveralls-github-action#:~:text=git%2Dcommit,the%20commit%20SHA.) input options that will trick the integration into thinking it's sending a report from your original PR branch, on behalf of the PR HEAD commit.

I'm familiar with the `workflow_run` trigger and how the triggered jobs must run in the default branch context (`master` in your case), and I've found it really cumbersome. 

Good luck with that and let us know how it goes!

**Comment by elchininet** [comment]
Hi @afinetooth,

I use [the master branch](https://github.com/elchininet/custom-sidebar/blob/e2e4ed6b99adc03e3747de53ff7e1ab87e04968a/.github/workflows/tests.yaml#L35) so it should be the latest one. But it was failing when I used `github.event.workflow_run.head_branch` and `github.event.workflow_run.head_sha` in the `workflow_run` job. I think that the reason is that Coveralls uses as `git-commit` `GITHUB_SHA` and this is the last merge commit of the pull request merge branch instead of the last commit id of the pull request.

**Comment by afinetooth** [comment]
@elchininet one more trick that might be your quickest solution:

**This is for use directly in your original workflow, not the one triggered by `workflow_run`**:

You can "trick" the Coveralls API by setting the incoming `service_name` parameter to anything else besides `github`, such as `github-actions`, and using the [Coveralls Repo Token](https://docs.coveralls.io/api-jobs-endpoint#authentication-coveralls-repo-token) to identify your repo, skipping the need for the GitHub Secret. (Explanation below.)

If you go this route, I'd suggest using [coverage-reporter](https://github.com/coverallsapp/coverage-reporter) directly in your workflow without using the [Coveralls GItHub Action](https://github.com/marketplace/actions/coveralls-github-action), but below are instructions for both:

### Using Coverage Reporter directly

```
  - name: Submit Coverage to Coveralls
     run: |
       curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin
       coveralls report --service-name=github-actions --repo-token=<YOUR_COVERALLS_REPO_TOKEN>
```

**Notes**:

- _If you're installing on other platforms, see Coverage Reporter [Installation](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#install) instructions._
- _If you want to pass additional parameters, see Coverage Reporter [Usage](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#usage) instructions._

### Using the Coveralls GitHub Action

```
  - name: Coveralls
    env:
      COVERALLS_SERVICE_NAME: github-actions
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }} # Add this to your GitHub secrets
    uses: coverallsapp/github-action@v2
```

**Notes**: 

- _This method is using Coveralls environment variables in your `env:` key. I chose this method because passing `COVERALL_SERVICE_NAME` is the only way to override `service_name: github` with the GitHub Action; so I figured why not use it for both. Your other option is to use the `with:` key and pass `github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}`._
- _I have treated your `COVERALLS_REPO_TOKEN` as though it's a secret in your repo, which you may want to do, and then you'll need to grant read-only access to it to forks; but since your repo is public, you may also just want to use directly as a string in your workflow. It's not best practice, but it will work if you're not too concerned about security.)_

## Explanation for this approach
The Coveralls API only requires a **GitHub Actions Secret** to identify an incoming repo when it thinks the upload is coming from **GitHub Actions**, for which nearly all Coveralls Integrations automatically populate `github` for the incoming `service_name` parameter in the JSON sent to our API.

But our API will take a _different_ form of identification for your Repo, its [Coveralls Repo Token](https://docs.coveralls.io/api-jobs-endpoint#authentication-coveralls-repo-token), if it thinks the report is coming  from a _different_ CI service.

**Comment by afinetooth** [comment]
Hi @elchininet 

Maybe see if one of the options above suit you better.

In the meantime, to answer:

> I use [the master branch](https://github.com/elchininet/custom-sidebar/blob/e2e4ed6b99adc03e3747de53ff7e1ab87e04968a/.github/workflows/tests.yaml#L35) so it should be the latest one. But it was failing when I used github.event.workflow_run.head_branch and github.event.workflow_run.head_sha in the workflow_run job. I think that the reason is that Coveralls uses as git-commit GITHUB_SHA and this is the last merge commit of the pull request merge branch instead of the last commit id of the pull request.

Yes, that is true. The commit SHA of a `pull_request` build will be the temporary HEAD of the PR's merge branch.

That should be OK as long as Coveralls knows that the incoming build should be treated as a `pull_request` build, which means it needs to see an incoming JSON parameter in its upload, like: `"service_pull_request": "234"`.

The GitHub Action typically handles that itself, but you should be able to fake it by adding this [COVERALLS Environment Variable](https://github.com/coverallsapp/coverage-reporter/blob/master/doc/configuration.md#env-variables) to your `env:` key:

```
  - name: Coveralls
    env:
      COVERALLS_PULL_REQUEST: <PR # FROM YOUR PR BUILD>
    uses: coverallsapp/github-action@v2
    with:
      github-token: ${{ secrets.COVERALLS_REPO_TOKEN }} # Add this to your GitHub secrets
```

**Comment by afinetooth** [comment]
@elchininet feel free to share your current workflow. I can probably offer more cogent suggestions by editing what you have.

**Comment by elchininet** [comment]
Hi @afinetooth,
Very good info, thanks👌🏼
I deleted everything and rolled back my branch to the beginning so I lost all the changes.
Feel free to close this issue, I think that I have everything to experiment with your answer.
Regards

**Comment by afinetooth** [comment]
@elchininet OK, great.

One more thing:

I'm down the rabbit hole on this a bit, but I think you might have a few other options to get around the need for a `workflow_run`-triggered workflow.

If you check out this doc:
[Modifying the permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)

It says:

> You can use the permissions key to add and remove read permissions for forked repositories, but typically you can't grant write access. The exception to this behavior is where an admin user has selected the **Send write tokens to workflows from pull requests** option in the GitHub Actions settings. For more information, see "[Managing GitHub Actions settings for a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks)."

Unfortunately, I can't find that "**Send write tokens to workflows from pull requests**" setting in the Actions settings for any repo I'm an Admin of, so that doc might be outdated.

But in any case, presuming it's possible to give permission to forked repos to _leverage_ your `GITHUB_TOKEN` for the purpose of submitting a coverage report to Coveralls, which I _think_ should only mean `read` access(?), it _should_ be possible for a forked PR on your public repo to use a workflow that passes your `GITHUB_TOKEN` as an input. 

Given it's best practice to limit these `permissions` to the job level, per:

> The two workflow examples earlier in this article show the permissions key being used at the job level, as it is best practice to limit the permissions' scope.

Something like this:

```
jobs:
  permissions:
    actions: read
  [...]
  - name: Run Tests
    [...]
  - name: Coveralls Upload
    uses: coverallsapp/github-action@v2
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
```

I'm not even sure `actions:read` is the [correct permission](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) for "pull requests from
public forked repositories". All I'm thinking here is that:

1. You have a public repo.
2. It _should_ be possible to give a forked PR permission to, at least, `read` your `GITHUB_TOKEN`.
3. Therefore, a forked PR should be able to populate the `github-token` param in a "Coveralls Upload" step, like the one above.

**Comment by afinetooth** [comment]
Yeah, sorry. I hope you get it to work with minimal changes.

I'll close this for now. Just re-open if you hit another issue.
